---
- name: add gpg key
  apt_key:
    url: https://nginx.org/keys/nginx_signing.key

- name: add deb repository
  template:
    src: sources.list.j2
    dest: /etc/apt/sources.list.d/nginx.list

- name: install package
  apt:
    name: nginx
    update_cache: yes

- name: install xslt module
  apt:
    name: nginx-module-xslt
  when: directory_indexes is defined

- name: install configuration
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - restart nginx

- name: remove default site
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent
  notify:
    - restart nginx

- name: create dhparam
  command:
    cmd: openssl dhparam -dsaparam -out /etc/nginx/dhparam-{{ item[0] }}.pem 4096
    creates: /etc/nginx/dhparam-{{ item[0] }}.pem
  loop: "{{ ssl_certificates }}"
  when: ssl_certificates is defined
  notify:
    - restart nginx

- name: create https configuration (no hsts)
  template:
    src: https-no-hsts.conf.j2
    dest: /etc/nginx/https-{{ item[0] }}-no-hsts.conf
  loop: "{{ ssl_certificates }}"
  when: ssl_certificates is defined
  notify:
    - restart nginx

- name: create https configuration
  template:
    src: https.conf.j2
    dest: /etc/nginx/https-{{ item[0] }}.conf
  loop: "{{ ssl_certificates }}"
  when: ssl_certificates is defined
  notify:
    - restart nginx

- name: create default domain server
  template:
    src: 00-default-server.conf.j2
    dest: /etc/nginx/conf.d/00-default-server.conf
  notify:
    - restart nginx

- name: create https redirect
  template:
    src: 00-https-redirect.conf.j2
    dest: /etc/nginx/conf.d/00-https-redirect.conf
  when: ssl_certificates is defined
  notify:
    - restart nginx

- name: install host redirect configurations
  template:
    src: nginx-redirect.conf.j2
    dest: /etc/nginx/conf.d/05-{{ item.name }}-redirect.conf
  loop: "{{ redirect_hosts }}"
  when: redirect_hosts is defined
  notify:
    - restart nginx

- name: copy index.xslt template
  copy:
    src: index.xslt
    dest: /var/www/index.xslt
  when: directory_indexes is defined
  notify:
    - restart nginx

- name: install directory index configurations
  template:
    src: nginx-index.conf.j2
    dest: /etc/nginx/conf.d/05-{{ item.name }}-index.conf
  loop: "{{ directory_indexes }}"
  when: directory_indexes is defined
  notify:
    - restart nginx
