---
- name: create systemd service
  template:
    src: filebin.service.j2
    dest: /etc/systemd/system/filebin.service
  notify:
    - restart filebin

- name: download distfile
  include_role:
    name: distfile
  vars:
    distfile_name: filebin
    distfile_file_prefix: filebin-static-linux-amd64-
    distfile_file_extension: .tar.xz
    distfile_service_name: filebin
    distfile_bin:
      - filebin
    distfile_data:
      magic.mgc: /usr/local/share

- name: install nginx configuration
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/conf.d/90-{{ filebin_server_name }}.conf
  notify:
    - restart nginx
