---
- name: install gpg
  apt:
    name: gpg
    state: latest
    update_cache: yes

- name: add caddy gpg key
  apt_key:
    url: https://dl.cloudsmith.io/public/caddy/stable/cfg/gpg/gpg.155B6D79CA56EA34.key

- name: add caddy deb repository
  get_url:
    url: https://dl.cloudsmith.io/public/caddy/stable/cfg/setup/config.deb.txt?distro=debian&version=any-version
    dest: /etc/apt/sources.list.d/caddy-stable.list

- name: install caddy
  apt:
    name: caddy
    state: latest
    update_cache: yes

- name: create /etc/caddy/sites-enabled, if needed
  file:
    path: /etc/caddy/sites-enabled
    state: directory

- name: install caddy configuration
  template:
    src: templates/Caddyfile.j2
    dest: /etc/caddy/Caddyfile
  notify:
    - restart caddy

- name: backup /var/lib/caddy
  copy:
    content: "/var/lib/caddy\n"
    dest: /etc/tarsnap.d/caddy
