---
- name: clone or update git repository
  git:
    repo: https://github.com/rafaelmartins/ledns.git
    dest: /var/build/ledns
  register: ledns_git
  when: distfiles_listen_addr is defined

- name: check if binary exists
  stat:
    path: /usr/local/bin/ledns
  register: ledns_bin
  when: distfiles_listen_addr is defined

- name: install golang
  apt:
    name: golang
    default_release: "{{ debian_codename }}-backports"
    update_cache: yes
    state: latest
  when: distfiles_listen_addr is defined and (ledns_git.changed or not ledns_bin.stat.exists)

- name: build binary
  command:
    cmd: go build -o /usr/local/bin/ledns
    chdir: /var/build/ledns
  when: distfiles_listen_addr is defined and (ledns_git.changed or not ledns_bin.stat.exists)

- name: download distfile
  include_role:
    name: distfile
  vars:
    distfile_name: ledns
    distfile_file_prefix: ledns-linux-amd64-
    distfile_bin:
      - ledns
  when: distfiles_listen_addr is not defined

- name: ensure configuration directory exists
  file:
    path: /etc/ledns.d
    state: directory

- name: ensure data directory exists
  file:
    path: /var/lib/ledns
    state: directory

- name: create global configuration
  copy:
    content: "{% for cert in ssl_certificates %}\n{{ cert|join(' ') }}\n{% endfor %}"
    dest: /etc/ledns.d/00-global
  when: ssl_certificates is defined
  notify: start ledns

- name: create systemd service
  template:
    src: ledns.service.j2
    dest: /etc/systemd/system/ledns.service

- name: copy systemd timer
  copy:
    src: files/ledns.timer
    dest: /etc/systemd/system/ledns.timer

- name: enable and start systemd timer
  systemd:
    name: ledns.timer
    enabled: yes
    state: started
    daemon_reload: yes

- name: backup data directory
  copy:
    content: "/var/lib/ledns\n"
    dest: /etc/tarsnap.d/ledns
