---
- name: add deb repository
  template:
    src: sources.list.j2
    dest: /etc/apt/sources.list.d/blogc.list

- name: install packages
  apt:
    pkg:
      - blogc-git-receiver
      - blogc-make
      - make
    update_cache: yes

- name: add user
  become: yes
  user:
    name: blogc
    shell: /usr/bin/blogc-git-receiver

- name: create ssh directory, if needed
  file:
    path: /home/blogc/.ssh
    state: directory
    owner: blogc
    group: blogc
    mode: '0700'

- name: download ssh keys from github
  get_url:
    url: https://github.com/{{ bgr_ssh_github_user }}.keys
    dest: /home/blogc/.ssh/authorized_keys
    owner: blogc
    group: blogc
    mode: '0600'
  when: bgr_ssh_github_user is defined

- name: install configuration
  template:
    src: blogc-git-receiver.ini.j2
    dest: /home/blogc/blogc-git-receiver.ini
    owner: blogc
    group: blogc

- name: install nginx configurations
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/conf.d/50-{{ item.name }}.conf
  loop: "{{ bgr_websites }}"
  notify:
    - restart nginx

- name: backup /home/blogc
  copy:
    content: "/home/blogc\n"
    dest: /etc/tarsnap.d/blogc-git-receiver
