---
- name: clone or update git repository
  git:
    repo: https://github.com/rafaelmartins/telegram-notify.git
    dest: /var/build/telegram-notify
  register: telegram_notify_git
  when: distfiles_listen_addr is defined

- name: check if binary exists
  stat:
    path: /usr/local/bin/telegram-notify
  register: telegram_notify_bin
  when: distfiles_listen_addr is defined

- name: install golang
  apt:
    name: golang
    default_release: "{{ debian_codename }}-backports"
    update_cache: yes
    state: latest
  when: distfiles_listen_addr is defined and (telegram_notify_git.changed or not telegram_notify_bin.stat.exists)

- name: build binary
  command:
    cmd: go build -o /usr/local/bin/telegram-notify
    chdir: /var/build/telegram-notify
  when: distfiles_listen_addr is defined and (telegram_notify_git.changed or not telegram_notify_bin.stat.exists)

- name: download distfile
  include_role:
    name: distfile
  vars:
    distfile_name: telegram-notify
    distfile_file_prefix: telegram-notify-linux-amd64-
    distfile_bin:
      - telegram-notify
  when: distfiles_listen_addr is not defined
